#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

## {{ Set up error handler.
if [ "$(type -t errorhandlergeneral)" = "function" ]; then
   ## Function errorhandlergeneral exists (declared in
   ## help-steps/pre). Prefer to use the more feature rich version of the error
   ## handler.
   trap "errorhandlergeneral" ERR
else
   ## Function errorhandlergeneral does not exist. Script
   ## runs standalone outside the build script. Fall back to a simpler error
   ## handler.
   trap "error_handler" ERR
fi
## }}

own_filename="$(basename "$BASH_SOURCE")"
for skip_script in $SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

if [ "$anon_shared_inst_tb" = "none" ]; then
   true "INFO: Skipping installation of Tor Browser as requested."
elif [ "$anon_shared_inst_tb" = "closed" ]; then
   true "INFO: Trying to install Tor Browser..."
   ## Building in the clear and behind a transparent Tor proxy is supported.
   ## In case we are not behind a Gateway with dedicated ports for
   ## Tor Browser download, use TransPort or clear download instead of SocksPort.
   ## Depends on working internet connection.
   sudo -u user /usr/bin/update-torbrowser --devbuildpassthrough
   true "INFO: Installation of Tor Browser succeeded."
elif [ "$anon_shared_inst_tb" = "open" ]; then
   true "INFO: Trying to install Tor Browser..."
   sudo -u user /usr/bin/update-torbrowser --devbuildpassthrough \
      || true "${bold}${red}ERROR: update-torbrowser exited $?, failed! Requested to fail open. Continuing...${reset}"
   true "INFO: Installation of Tor Browser succeeded."
else
   true "INFO: Skipping installation of Tor Browser, because variable \
anon_shared_inst_tb is neither set to none, closed or open (see --tb)."
fi

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
